name: update_databases
on:
  schedule:
    # We should monitor this to see if it's enough to wait for the 4th day
    # according to the mtime of the gzip it's created on the first day of the
    # month at 30 minutes past midnight.
    # Note: it get's disabled after 60 days of no pushes to this repo.
    - cron: "0 2 1-4 * *"
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_databases:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: cache inputs and outputs
        uses: actions/cache@v4
        with:
          key: update_databases_inputs_outputs
          path: |
            ~/cache_dir
            ~/outputs

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.18.0"
          cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - run: pip install -r requirements.txt

      - run: ./update_databases.sh
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
